[build]
  command = "npm run build"
  publish = ".next"

# The following plugin is automatically installed by Netlify for Next.js apps,
# but we include it here for clarity and version control.
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
